### ISSUE TITLE
Escribir un buen template de ISSUE en Github

### ISSUE THREAD

**Issue by abenassi** [datosgobar/cookiecutter-pypackage-ar#1]
@pilimayora @solpar  en el template de repo hay una carpeta `.github` que tiene un archivo `ISSUE_TEMPLATE.md`. Ese template es tomado por Github cada vez que un usuario quiere hacer un issue a tu repo, para que arranque con eso.

Podríamos pensar un par de elementos que quisiéramos que *siempre/casi siempre* tenga un issue que nos carguen ;-)

**Comment by pilimayora** [comment]
Este tema ya lo resolvimos :) cc @solpar @abenassi
